# Cloudflare Worker configuration for Zip-City Lookup
name = "zip-city-lookup"
main = "src/index.js"
compatibility_date = "2025-07-16"

# Workers KV namespaces (optional - for future migration from R2)
# Uncomment and configure when migrating to KV storage:
# Create with: wrangler kv namespace create "ZIP_US"
# [[kv_namespaces]]
# binding = "ZIP_US"
# id = "your-us-zipcode-kv-namespace-id"
# preview_id = "your-us-zipcode-preview-kv-namespace-id"

# [[kv_namespaces]]
# binding = "ZIP_CA"
# id = "your-ca-zipcode-kv-namespace-id"
# preview_id = "your-ca-zipcode-preview-kv-namespace-id"

# R2 bucket bindings (currently active)
# Created with: wrangler r2 bucket create zipcity
[[r2_buckets]]
binding = "ZIP_DATA"
bucket_name = "zipcity"

[[d1_databases]]
binding = "DB"
database_name = "zipcity-data"
database_id = "5ea45c91-9c2b-4c85-a39f-285932fe9207"

# Custom domain routing (active)
# DNS CNAME: zipcity.iwpi.com -> zip-city-lookup.paul-bb4.workers.dev
[[routes]]
pattern = "zipcity.iwpi.com/api/*"
zone_name = "iwpi.com"

[vars]
# Environment variables (if needed)
# API_VERSION = "1.0"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.